#!/bin/bash
case "$1" in
  send)
    echo
    echo "$0 called with $@"
    echo "stdin:"
    cat
    echo
  ;;
  sendfile)
    echo
    echo "$0 called with:"
    echo "$@"
    cp -v "$2" .
    echo
  ;;
  *)
    echo "ERROR unknown command: $0 $@"
  ;;
esac
